# -*- coding: utf-8 -*-
"""Aplicação Flask

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP8N_sF-ayVImi-6TUmKf3QZuJy_Fn2G
"""

from flask import Flask, render_template

# Inicializa a aplicação Flask
app = Flask(__name__)

# Define a rota principal da aplicação
@app.route('/')
def home():
    """
    Renderiza a página principal da loja de aplicativos.
    """
    return render_template('choco_web_store.html')

# Bloco para permitir a execução local para testes
if __name__ == '__main__':
    app.run(debug=True)